---
# tasks file for tomcat
- debug: msg="installing tomcat"

- name: install the 'Development Tools' package group
  yum: name="@Development tools" state=present

- name: creating sudoers.d file
  copy: src=tomcat dest=/etc/sudoers.d/

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/opt/apache-tomcat-7.0.68 createhome=no
  sudo: True

- name: download tomcat
  get_url: url=http://ftp.byfly.by/pub/apache.org/tomcat/tomcat-7/v7.0.68/bin/apache-tomcat-7.0.68.tar.gz dest=/opt/apache-tomcat-7.0.68.tar.gz

- name: extract tomcat archive
  unarchive: src=/opt/apache-tomcat-7.0.68.tar.gz dest=/opt/ copy=no creates=/opt/apache-tomcat-7.0.68

- name: change ownership of tomcat installation
  file: path=/opt/apache-tomcat-7.0.68/ owner=tomcat group=tomcat state=directory recurse=yes

- name: install tomcat init script
  copy: src=tomcat-init.sh dest=/etc/init.d/tomcat mode=0755

- name: configure tomcat server
  template: src=server.xml dest=/opt/apache-tomcat-7.0.68/conf/

- name: start tomcat
  service: name=tomcat state=started enabled=yes



