- name: Aliaksandr_Karavai_play_1
  hosts: all
  become: yes
  tasks:
     - name: install java1.7 tomcat7
       yum: name={{ item }} state=installed
       with_items:
            - tomcat
            - tomcat-webapps
            - java-1.7.0-openjdk-devel
            - git
       notify: tomcat enabled
     - copy: src=server.xml dest=/etc/tomcat/
     - name: install nginx repo
       yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
     - name: install nginx
       yum: name=nginx state=latest
     - copy: src=default.conf dest=/etc/nginx/conf.d/
     - name: jenkins install key
       rpm_key: state=present key=https://jenkins-ci.org/redhat/jenkins-ci.org.key validate_certs=no
     - name: install jenkins rep
       get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo validate_certs=no
     - name: jenkins install
       yum: name=jenkins state=latest
     - copy: src=jenkins dest=/etc/sysconfig/jenkins
     - copy: src=jenkinsconfig dest=/var/lib/jenkins/config.xml
     - user: name=jenkins groups=tomcat
     - copy: src=plugins dest=/var/lib/jenkins
     - copy: src=jobs dest=/var/lib/jenkins
     - copy: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins
     - file: path=/var/lib/jenkins owner=jenkins group=jenkins recurse=yes
     - file: path=/var/lib/tomcat/webapps mode=0777
     - name: Starting Jenkins after copy jobs
       service: name=jenkins state=running enabled=yes
     - name: Starting nginx after copy new congig
       service: name=nginx state=running enabled=yes
  handlers:
     - name: tomcat enabled
       service: name=tomcat state=running enabled=yes
