- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    services_info: |
      Jenkins URL - http://localhost:8080/jenkins/
      Jenkins Delivery - http://localhost:8080/jenkins/view/Pet%20CD/
      Application URL - http://localhost:8080/mnt-lab/

  pre_tasks:
  - debug: msg="Let's do this"

  tasks:

  - name: downloading jenkins repo
    get_url: url=http://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  - name: jenkins repo key
    rpm_key: state=present key=http://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Instaling packages
    yum: name={{ item.name }} state={{ item.state| default("latest") }}
    with_items:
      - {name: "http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm", state: "installed"} 
      - {name: "java-1.7.0-openjdk-devel", state: "present"}
      - {name: "nginx"} 
      - {name: "tomcat"} 
      - {name: "jenkins"} 
      - {name: "git"}
      - {name: "tomcat-webapps"}

  - name: copying config files
    copy: src={{ item.src }} dest={{ item.dest }} force={{ item.force| default("yes")}}
    with_items:
      - {src: "virtual.conf", dest: "/etc/nginx/conf.d/"}
      - {src: "server.xml", dest: "/usr/share/tomcat/conf/"}
      - {src: "jenkins", dest: "/etc/sysconfig/"}
      - {src: "config.xml", dest: "/var/lib/jenkins/"}
      - {src: "hudson.tasks.Maven.xml", dest: "/var/lib/jenkins/"}
      - {src: "plugins", dest: "/var/lib/jenkins", force: "no"}
      - {src: "jobs", dest: "/var/lib/jenkins", force: "no"}

  - name: JENKINS | changing jenkins user group
    user: name=jenkins groups=tomcat
  - name: JENKINS | chown
    file: path=/var/lib/jenkins owner=jenkins group=jenkins recurse=yes

  - name: starting services
    service: name={{ item }} state=started enabled=yes
    with_items:
      - nginx
      - tomcat
      - jenkins

  post_tasks:
  - debug: var=services_info.split('\n')
