- name: Ansible test
  hosts: all
  become: yes

  tasks:
    - name: Install Java 1.7
      yum: name=java-1.7.0-openjdk-devel state=installed
    - name: Installing git
      yum: name=git state=latest
# Nginx
    - name: NGINX | Installing NGINX repo rpm
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    - name: Nginx | Nginx install
      yum: name=nginx state=latest
    - name: changing nginx config
      copy: src=src/virtual.conf dest=/etc/nginx/conf.d/virtual.conf
# Tomcat
    - name: Tomcat install
      yum: name=tomcat state=latest
    - name: tomcat-webapps
      yum: name=tomcat-webapps state=latest
    - name: Copy config
      template: src=src/server.xml dest=/etc/tomcat/server.xml
    - name: chmod webapps
      command: chmod -R 777 /var/lib/tomcat/webapps/
# add sudoers   
    - name: Copying Jenkins-user sudoers file
      copy: src=src/jenkins-user dest=/etc/sudoers.d/ force=no

# Jenkins
    - name: jenkins wget
      command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    - name: jenkins rpm
      command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    - name: jenkins install
      yum: name=jenkins
    - name: Copy config
      template: src=src/config.xml dest=/var/lib/jenkins/config.xml    
    - name: Copy jenkins config
      template: src=src/jenkins dest=/etc/sysconfig/jenkins
    - name: Copying Maven config for Jenkins
      copy: src=src/hudson.tasks.Maven.xml dest=/var/lib/jenkins/ force=no
    - name: Jobs for Jenkins
      copy: src=src/jobs dest=/var/lib/jenkins/ force=no
    - name: Plugins for Jenkins
      copy: src=src/plugins dest=/var/lib/jenkins/ force=no
    - name: chown
      command: chown -R jenkins.jenkins /var/lib/jenkins
# Starting apps 
    - name: jenkins start
      service: name=jenkins state=running
    - name: NGINX | Starting nginx
      service: name=nginx state=running
    - name: Tomcat start
      service: name=tomcat state=running

