- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/opt/apache/ createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.8/bin/apache-tomcat-7.0.8.tar.gz dest=/opt/apache/apache-tomcat-7.0.8.tar.gz

- name: Extract archive
  command: chdir=/opt/apache/tomcat /bin/tar xvf /opt/apache/apache-tomcat-7.0.61.tar.gz -C /opt/apache creates=/opt/apache/apache-tomcat-7.0.61

- name: Symlink install directory
  file: src=/opt/apache/apache-tomcat-7.0.61 path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

sudo sed -i.bac 's/"8080"/"9090"/g' /usr/share/tomcat/conf/server.xml 
